### ISSUE TITLE
Docker-Compose

### ISSUE THREAD

**Issue by Nightwielder1** [kmille/deezer-downloader#67]
I'm having issues deploying via docker-compose. Please advise. This is my compose file:

```
---
version: '2'

services:
  deezer-downloader:
    image: kmille2/deezer-downloader
    environment:
      - DEEZER_COOKIE_ARL=<arl>
      - DEEZER_FLAC_QUALITY=True
    volumes:
      - /mnt/md0/Music/Collection:/mnt/deezer-downloader
    ports:
      - "8686:5000"
```
